const growth_db = [
    {
        id: 0,
        common_names: ['Airplant', 'Sky plant', 'Blushing Bride'],
        scien_name: 'Tillandsia ionantha Planch',
        genus: 'Tillandsia',
        family: 'Bromeliaceae',
        life_cycle: 'Perennial',
        sun_requirements: 'Full Sun to Partial Shade', // rename this to something else
        leaves: 'Evergreen, Leaves are typically gray, gray-green, or white',
        locations: 'Terrariums',
        misc: 'Epiphytic',
    },
    {
        id: 1,
        common_names: ['Airplant1', 'Sky plant1', 'Blushing Bride1'],
        scien_name: 'Tillandsia ionantha Planch1',
        genus: 'Hemerocallis1',
        family: 'Hemerocallidaceae1',
        species: 'fulva1', // not needed?
        life_cycle: 'Perennial1',
        sun_requirements: 'Full Sun to Partial Shade1', // rename this to something else
        leaves: '1Evergreen, Leaves are typically gray, gray-green, or white',
        locations: '1Terrariums',
        misc: '1Epiphytic',
    },
    {
        id: 2,
        common_names: ['Airplant1', 'Sky plant1', 'Blushing Bride1'],
        scien_name: 'Tillandsia ionantha Planch1',
        genus: 'Hemerocallis1',
        family: 'Hemerocallidaceae1',
        species: 'fulva1', // not needed?
        life_cycle: 'Perennial1',
        sun_requirements: 'Full Sun to Partial Shade1', // rename this to something else
        leaves: '1Evergreen, Leaves are typically gray, gray-green, or white',
        locations: '1Terrariums',
        misc: '1Epiphytic',
    },
    {
        id: 3,
        common_names: ['Airplant1', 'Sky plant1', 'Blushing Bride1'],
        scien_name: 'Tillandsia ionantha Planch1',
        genus: 'Hemerocallis1',
        family: 'Hemerocallidaceae1',
        species: 'fulva1', // not needed?
        life_cycle: 'Perennial1',
        sun_requirements: 'Full Sun to Partial Shade1', // rename this to something else
        leaves: '1Evergreen, Leaves are typically gray, gray-green, or white',
        locations: '1Terrariums',
        misc: '1Epiphytic',
    },
    {
        id: 4,
        common_names: ['Airplant1', 'Sky plant1', 'Blushing Bride1'],
        scien_name: 'Tillandsia ionantha Planch1',
        genus: 'Hemerocallis1',
        family: 'Hemerocallidaceae1',
        species: 'fulva1', // not needed?
        life_cycle: 'Perennial1',
        sun_requirements: 'Full Sun to Partial Shade1', // rename this to something else
        leaves: '1Evergreen, Leaves are typically gray, gray-green, or white',
        locations: '1Terrariums',
        misc: '1Epiphytic',
    },
    {
        id: 5,
        common_names: ['Airplant1', 'Sky plant1', 'Blushing Bride1'],
        scien_name: 'Tillandsia ionantha Planch1',
        genus: 'Hemerocallis1',
        family: 'Hemerocallidaceae1',
        species: 'fulva1', // not needed?
        life_cycle: 'Perennial1',
        sun_requirements: 'Full Sun to Partial Shade1', // rename this to something else
        leaves: '1Evergreen, Leaves are typically gray, gray-green, or white',
        locations: '1Terrariums',
        misc: '1Epiphytic',
    },
    {
        id: 6,
        common_names: ['Airplant1', 'Sky plant1', 'Blushing Bride1'],
        scien_name: 'Tillandsia ionantha Planch1',
        genus: 'Hemerocallis1',
        family: 'Hemerocallidaceae1',
        species: 'fulva1', // not needed?
        life_cycle: 'Perennial1',
        sun_requirements: 'Full Sun to Partial Shade1', // rename this to something else
        leaves: '1Evergreen, Leaves are typically gray, gray-green, or white',
        locations: '1Terrariums',
        misc: '1Epiphytic',
    },
    {
        id: 7,
        common_names: ['Airplant1', 'Sky plant1', 'Blushing Bride1'],
        scien_name: 'Tillandsia ionantha Planch1',
        genus: 'Hemerocallis1',
        family: 'Hemerocallidaceae1',
        species: 'fulva1', // not needed?
        life_cycle: 'Perennial1',
        sun_requirements: 'Full Sun to Partial Shade1', // rename this to something else
        leaves: '1Evergreen, Leaves are typically gray, gray-green, or white',
        locations: '1Terrariums',
        misc: '1Epiphytic',
    },
    {
        id: 8,
        common_names: ['Airplant1', 'Sky plant1', 'Blushing Bride1'],
        scien_name: 'Tillandsia ionantha Planch1',
        genus: 'Hemerocallis1',
        family: 'Hemerocallidaceae1',
        species: 'fulva1', // not needed?
        life_cycle: 'Perennial1',
        sun_requirements: 'Full Sun to Partial Shade1', // rename this to something else
        leaves: '1Evergreen, Leaves are typically gray, gray-green, or white',
        locations: '1Terrariums',
        misc: '1Epiphytic',
    },
    {
        id: 9,
        common_names: ['Airplant1', 'Sky plant1', 'Blushing Bride1'],
        scien_name: 'Tillandsia ionantha Planch1',
        genus: 'Hemerocallis1',
        family: 'Hemerocallidaceae1',
        species: 'fulva1', // not needed?
        life_cycle: 'Perennial1',
        sun_requirements: 'Full Sun to Partial Shade1', // rename this to something else
        leaves: '1Evergreen, Leaves are typically gray, gray-green, or white',
        locations: '1Terrariums',
        misc: '1Epiphytic',
    },
    {
        id: 10,
        common_names: ['Airplant1', 'Sky plant1', 'Blushing Bride1'],
        scien_name: 'Tillandsia ionantha Planch1',
        genus: 'Hemerocallis1',
        family: 'Hemerocallidaceae1',
        species: 'fulva1', // not needed?
        life_cycle: 'Perennial1',
        sun_requirements: 'Full Sun to Partial Shade1', // rename this to something else
        leaves: '1Evergreen, Leaves are typically gray, gray-green, or white',
        locations: '1Terrariums',
        misc: '1Epiphytic',
    },
]

/*
Height: '24-36 in. (60-90 cm)'

Spacing: '15-18 in. (38-45 cm)'

Hardiness:
['USDA Zone 5a: to -28.8 °C (-20 °F)', 
'USDA Zone 5b: to -26.1 °C (-15 °F)', 
'USDA Zone 6a: to -23.3 °C (-10 °F)', 
'USDA Zone 6b: to -20.5 °C (-5 °F)', 
'USDA Zone 7a: to -17.7 °C (0 °F)', 
'USDA Zone 7b: to -14.9 °C (5 °F)', 
'USDA Zone 8a: to -12.2 °C (10 °F)', 
'USDA Zone 8b: to -9.4 °C (15 °F)', 
'USDA Zone 9a: to -6.6 °C (20 °F)', 
'USDA Zone 9b: to -3.8 °C (25 °F)', 
'USDA Zone 10a: to -1.1 °C (30 °F)', 
'USDA Zone 10b: to 1.7 °C (35 °F)']

Sun Exposure: ['Full Sun', 'Sun to Partial Shade']

Soil pH requirements: 
['6.1 to 6.5 (mildly acidic)',
'6.6 to 7.5 (neutral)',
'7.6 to 7.8 (mildly alkaline)']

Patent Information: 'Non-patented'

Propagation Methods: 'By dividing the rootball'

Bloom Time: ['Early (E)', 'Reblooming (Re)']

Flower Size: 'Large (more than 4.5" diameter)'

Blooming Habit: 'Diurnal (diu.)'

Flower Type: 'Single'

Bloom Color: 'Orange'

Color Patterns: 'Blend'

Flower Fragrance: 'Slightly Fragrant'

Foliage Habit: 'Semi-evergreen (sev.)'

Ploidy: Unknown

Awards (if applicable): Unknown

Foliage Color: Unknown

Bloom Characteristics: Unknown

Water Requirements:
'Average Water Needs; Water regularly; do not overwater'

Where to Grow:
'Grow outdoors year-round in hardiness zone'

Regional
This plant is said to grow outdoors in the following regions:
['Auburn, Alabama(3 reports)', 
'Birmingham, Alabama', 
'Cullman, Alabama', 
'Gadsden, Alabama', 
'Huntsville, Alabama', 
'Madison, Alabama', 
'Mobile, Alabama(2 reports)', 
'Montgomery, Alabama', 
'Piedmont, Alabama', 
'Scottsboro, Alabama', 
'Vincent, Alabama', 
'Flagstaff, Arizona', 
'Bismarck, Arkansas', 
'Fayetteville, Arkansas', 
'Logan Lake, British Columbia', 
'Sacramento, California', 
'Santa Barbara, California', 
'Temecula, California', 
'Wildomar, California', 
'Colorado Springs, Colorado', 
'Denver, Colorado', 
'Laporte, Colorado', 
'Bear, Delaware', 
'Newark, Delaware', 
'Ocean View, Delaware', 
'Deltona, Florida', 
'Gibsonton, Florida', 
'Lake City, Florida', 
'Marianna, Florida', 
'Miccosukee Cpo, Florida', 
'Panama City, Florida', 
'Tallahassee, Florida', 
'Welaka, Florida', 
'Braselton, Georgia', 
'Canton, Georgia', 
'Cordele, Georgia', 
'Cornelia, Georgia', 
'Hawkinsville, Georgia', 
'Homer, Georgia', 
'Kingsland, Georgia', 
'Roopville, Georgia', 
'Snellville, Georgia', 
'Stone Mountain, Georgia', 
'Bensenville, Illinois', 
'Carterville, Illinois', 
'Champaign, Illinois', 
'Cherry Valley, Illinois', 
'Chillicothe, Illinois', 
'Hampton, Illinois', 
'Hinsdale, Illinois', 
'Mt Zion, Illinois', 
'Niles, Illinois', 
'Spring Grove, Illinois', 
'Farmersburg, Indiana', 
'Logansport, Indiana', 
'Macy, Indiana', 
'Newburgh, Indiana', 
'Solsberry, Indiana', 
'Cedar Rapids, Iowa', 
'Davenport, Iowa', 
'Iowa City, Iowa', 
'Nichols, Iowa', 
'Brookville, Kansas', 
'Barbourville, Kentucky', 
'Calvert City, Kentucky', 
'Ewing, Kentucky', 
'Fedscreek, Kentucky', 
'Hebron, Kentucky', 
'Lexington, Kentucky', 
'Louisville, Kentucky', 
'Mc Dowell, Kentucky', 
'Melbourne, Kentucky', 
'Paintsville, Kentucky', 
'Salvisa, Kentucky', 
'Smiths Grove, Kentucky', 
'Taylorsville, Kentucky', 
'Villers-lÃ¨s-Nancy, Lorraine', 
'Baton Rouge, Louisiana', 
'Coushatta, Louisiana', 
'Hessmer, Louisiana', 
'Monroe, Louisiana', 
'New Orleans, Louisiana', 
'Prairieville, Louisiana', 
'Zachary, Louisiana', 
'Durham, Maine', 
'Fort Kent, Maine', 
'Lisbon, Maine', 
'South Berwick, Maine', 
'Cumberland, Maryland', 
'Hughesville, Maryland', 
'Laurel, Maryland', 
'Pikesville, Maryland', 
'Amesbury, Massachusetts', 
'Bridgewater, Massachusetts', 
'Brimfield, Massachusetts', 
'Mashpee, Massachusetts', 
'Roslindale, Massachusetts', 
'Salem, Massachusetts', 
'Sandwich, Massachusetts', 
'Weston, Massachusetts', 
'Woburn, Massachusetts', 
'Caro, Michigan', 
'Davison, Michigan', 
'Dearborn Heights, Michigan', 
'Detroit, Michigan', 
'Eastpointe, Michigan', 
'Grand Rapids, Michigan', 
'Mancelona, Michigan', 
'Mount Morris, Michigan', 
'Pinconning, Michigan', 
'Plainwell, Michigan', 
'Royal Oak, Michigan', 
'Saginaw, Michigan', 
'Saint Clair Shores, Michigan', 
'South Lyon, Michigan', 
'Traverse City, Michigan', 
'Grand Portage, Minnesota', 
'Hibbing, Minnesota', 
'Minneapolis, Minnesota(3 reports)', 
'Sturgeon Lake, Minnesota', 
'Gulfport, Mississippi', 
'Madison, Mississippi', 
'Marietta, Mississippi', 
'Bates City, Missouri', 
'Cole Camp, Missouri', 
'Conway, Missouri', 
'Kansas City, Missouri', 
'Saint Louis, Missouri', 
'Springfield, Missouri', 
'Omaha, Nebraska', 
'Scottsbluff, Nebraska', 
'Colpitts Settlement, New Brunswick', 
'Auburn, New Hampshire', 
'Exeter, New Hampshire', 
'Greenville, New Hampshire', 
'Milford, New Hampshire', 
'Mont Vernon, New Hampshire', 
'Munsonville, New Hampshire', 
'Nashua, New Hampshire', 
'Newport, New Hampshire', 
'North Walpole, New Hampshire', 
'Neptune, New Jersey', 
'Vincentown, New Jersey', 
'Moriarty, New Mexico', 
'Roswell, New Mexico', 
'Santa Fe, New Mexico', 
'Taos, New Mexico', 
'Ballston Spa, New York', 
'Bronx, New York(2 reports)', 
'Churchville, New York', 
'Dundee, New York', 
'Eden, New York', 
'Elba, New York', 
'Greene, New York', 
'Hornell, New York', 
'Jefferson, New York', 
'Kew Gardens, New York', 
'New Hyde Park, New York', 
'Nineveh, New York', 
'North Tonawanda, New York', 
'Oceanside, New York', 
'Ogdensburg, New York', 
'Penn Yan, New York', 
'Rochester, New York', 
'Saranac Lake, New York', 
'Saratoga Springs, New York', 
'Syracuse, New York', 
'West Kill, New York', 
'Burlington, North Carolina', 
'Concord, North Carolina', 
'Denver, North Carolina', 
'Elizabeth City, North Carolina', 
'Fuquay Varina, North Carolina', 
'Graham, North Carolina', 
'Hillsborough, North Carolina', 
'Lake Toxaway, North Carolina', 
'Bucyrus, Ohio(2 reports)', 
'Chillicothe, Ohio', 
'Cincinnati, Ohio', 
'Columbus, Ohio', 
'Dayton, Ohio', 
'Defiance, Ohio', 
'Dundee, Ohio', 
'Elyria, Ohio', 
'Guysville, Ohio', 
'Lynchburg, Ohio', 
'Madison, Ohio', 
'Newark, Ohio', 
'North Ridgeville, Ohio', 
'Hulbert, Oklahoma', 
'Ninnekah, Oklahoma', 
'Greater Sudbury, Ontario', 
'Baker City, Oregon', 
'Blodgett, Oregon', 
'Altoona, Pennsylvania', 
'Doylestown, Pennsylvania', 
'Irwin, Pennsylvania', 
'Langhorne, Pennsylvania', 
'Millersburg, Pennsylvania', 
'Pottstown, Pennsylvania', 
'Upper Darby, Pennsylvania', 
'Valencia, Pennsylvania', 
'Watsontown, Pennsylvania', 
'West Chester, Pennsylvania', 
'West Warwick, Rhode Island(2 reports)', 
'Conway, South Carolina', 
'Prosperity, South Carolina', 
'Summerville, South Carolina', 
'Wagener, South Carolina', 
'Clarksville, Tennessee', 
'Clifton, Tennessee', 
'Elizabethton, Tennessee', 
'Hendersonville, Tennessee', 
'Hixson, Tennessee', 
'Memphis, Tennessee', 
'Murfreesboro, Tennessee', 
'Pocahontas, Tennessee', 
'Arlington, Texas', 
'Belton, Texas', 
'Channelview, Texas', 
'Colmesneil, Texas', 
'Conroe, Texas', 
'Coppell, Texas', 
'Dallas, Texas(2 reports)', 
'Desoto, Texas', 
'Fate, Texas', 
'Fort Worth, Texas', 
'Gainesville, Texas', 
'Galveston, Texas', 
'Gause, Texas', 
'Gilmer, Texas', 
'Kingsland, Texas', 
'Leander, Texas', 
'New Caney, Texas', 
'Palestine, Texas', 
'Port Neches, Texas', 
'Rowlett, Texas', 
'Centerville, Utah', 
'Salt Lake City, Utah(2 reports)', 
'Tremonton, Utah', 
'Montpelier, Vermont', 
'West Dummerston, Vermont', 
'Fancy Gap, Virginia', 
'Jonesville, Virginia', 
'Pulaski, Virginia', 
'Roanoke, Virginia', 
'Suffolk, Virginia', 
'Vienna, Virginia', 
'Virginia Beach, Virginia', 
'Wytheville, Virginia', 
'Kalama, Washington', 
'Olympia, Washington', 
'Spokane, Washington', 
'Stanwood, Washington', 
'Twisp, Washington', 
'Liberty, West Virginia', 
'Peterstown, West Virginia', 
'Dallas, Wisconsin', 
'Delavan, Wisconsin', 
'Ellsworth, Wisconsin', 
'Marinette, Wisconsin', 
'New Lisbon, Wisconsin', 
'New London, Wisconsin', 
'Ogema, Wisconsin', 
'Pewaukee, Wisconsin', 
'Pulaski, Wisconsin', 
'South Milwaukee, Wisconsin', 
'Casper, Wyoming', 
'Kinnear, Wyoming', 
'Riverton, Wyoming', 
'Sheridan, Wyoming']
*/

/*
Clockwise from bottom left (with an emphasis on native plants first in each line and then an option for non-native; native species may be all you want to include)
Sisyrinchium angustifolium; Myosotis scorpioides (those are the pale blue flowers)
Symphyotrichum novae-angliae or Polypodium virginianum (both are natives; the former is an aster; the latter is a fern – both would have leaves like the alternate-leaved stuff drawn here)
Chamerion angustifolium (native) or Gladiolus sp
(back pale flowers): Oenothera perennis (native) or  Primula vulgaris
(blue-purple flowers on the right): Amorpha canescens (native) or Phlox panicula
(middle bright purple flowers):  Eupatorium maculatum (native for wetter areas) or  Echinacea purpurea (drier areas; native) or Zinnia sp
Middle yellow flowers: Rudbeckia hirta (native)
*/