import blue_eyed_grass_img from '../assets/plant_images/blue_eyed_grass.jpg'
import rock_polypody_img from '../assets/plant_images/rock_polypody.jpg'
import fireweed_img from '../assets/plant_images/fireweed.jpeg'
import primrose_img from '../assets/plant_images/primrose.jpg'
import fall_phlox_img from '../assets/plant_images/fall_phlox.jpg'
import eastern_purple_coneflower_img from '../assets/plant_images/eastern_purple_coneflower.jpg'
import black_eyed_susan_img from '../assets/plant_images/black_eyed_susan.gif'

const plantDb = [
    {
        id: 0,
        imageUrl: blue_eyed_grass_img,
        commonNames: ['Narrowleaf Blue-eyed Grass', 'Narrow-leaf Blue-eyed-grass', 'Bermuda Blue-eyed Grass', 'Blue-eyed Grass'],
        scientificName: 'Sisyrinchium angustifolium',
        localities: ['BC', 'NS', 'PE', 'QC'],
        blooms: ['Mar', 'Apr', 'May', 'Jun', 'Jul'],
        establishmentMeans: 'Natural, Non-invasive',
        lifespan: 'Perennial',
        lightRequirements: ['Sun', 'Part Shade'],
        height: '12-18 inches',
        description: [
            'The numerous, narrow, light-green leaves of this perennial form dense, tufted clumps which steadily grow with new foliage during the season. The flattened, leaf-like flowering stems may be up to 18 in. long and bear light-blue, star-shaped flowers a few inches above the leaves. Height is 1-1 1/2 ft. Several delicate, blue or deep blue-violet flowers with yellow centers in 2 broad bracts top a flat stem, generally only 1 flower at a time in bloom; stems taller than the clusters of narrow, sword-shaped leaves near base.',
            'Although the plant is small and has grass-like leaves, the flowers have all the features of the Iris family. The various species are all much alike and separation is based on such characteristics as branching pattern and leaf length. Common Blue-eyed Grass (S. montanum) is also a widespread species, with slightly wider leaves, over 1/4" (6 mm), and unbranched stalks.'],
        waterAmount: ['Medium'],
        soilMoisture: ['Moist', 'Wet'],
        conditionComments: 'This short-lived perennial will decline if allowed to dry out. Heavy mulch causes crown rot and rich, organic soils encourage rank, vegetative growth. Plants need to be divided at least every other year.',
        spacing: '6 to 8 inches',
        seedDepth: '1 to 4 inches',
        plantingTime: 'Any',
        mainPreference: {warning: 'Location'},
        // TODO
        pros: [
            { name: 'Animals', state: 'Good' },
            { name: 'Time', state: 'Awful' },
            { name: 'Pollination', state: 'Awful' },
            { name: 'Cost', state: 'Excellent' },
        ],
        cons: [
            { name: 'Location', state: 'Poor' },
            { name: 'Children', state: 'Good' },
        ]
    },
    {
        id: 1,
        imageUrl: rock_polypody_img,
        commonNames: ['Rock Polypody'],
        scientificName: 'Polypodium virginianum',
        localities: ['MB', 'NB', 'NL', 'NS', 'NT', 'ON', 'PE', 'QC', 'SK'],
        blooms: ['N/A'],
        establishmentMeans: 'Natural, Non-invasive',
        lifespan: 'Perennial',
        lightRequirements: ['Shade', 'Part Shade'],
        height: '2-5 inches',
        description: [
            'Polypody is a creeping fern that forms dense mats and will cover mossy rocks. Fronds are small, leathery and evergreen.',
            'A good rock garden plant in filtered light.'],
        waterAmount: ['Low'],
        soilMoisture: ['Dry'],
        conditionComments: 'Will only tolerate moist soil with good drainage. ',
        spacing: '12 to 24 inches',
        seedDepth: '1 to 4 inches',
        plantingTime: 'Any',
        mainPreference: {warning: 'Location'},
        pros: [
            { name: 'Cost', state: 'Excellent' },
            { name: 'Animals', state: 'Good' },
        ],
        cons: [
            { name: 'Location', state: 'Awful' },
            { name: 'Pollination', state: 'Awful' },
            { name: 'Children', state: 'Poor' },
            { name: 'Time', state: 'Poor' },
        ]
    },
    {
        id: 2,
        imageUrl: fireweed_img,
        commonNames: ['Fireweed', 'Willow Herb', 'Great Willow Herb'],
        scientificName: 'Chamerion angustifolium',
        localities: ['AB', 'BC', 'MB', 'NB', 'NL', 'NS', 'NT', 'NU', 'ON', 'PE', 'QC', 'SK', 'YT '],
        blooms: ['Jun', 'Jul', 'Aug', 'Sep'],
        establishmentMeans: 'Natural, Non-invasive',
        lifespan: 'Perennial',
        lightRequirements: ['Shade', 'Part Shade', 'Sun'],
        height: '3-5 feet',
        description: [
            'Pink spires of flowers bloom at tops of tall, erect, leafy stems with narrow willow-like leaves.',
            'Often grows in spectacular dense patches, and though attractive, it is aggressive in a moist garden, spreading from persistent underground stems. The seeds are dispersed far and wide by long, white, silky hairs. Bees value it as a source of nectar, and the very young shoots and leaves can be eaten as cooked greens. Recent work at the genetic level has shown that Chamerion, recognized by its alternate leaves, is distinct from Epilobium (with leaves opposite, at least near base), the genus in which Fireweed was formerly placed.'],
        waterAmount: ['Low'],
        soilMoisture: ['Dry'],
        conditionComments: 'Disturbed soil in cool areas, from the lowlands well into the mountains, frequent along highways and in burned areas; hence one common name.',
        spacing: '3 to 6 inches',
        seedDepth: '1 to 4 inches',
        plantingTime: 'Any',
        mainPreference: {suggestion: 'Pollination'},
        pros: [ // BEES GREAT
            { name: 'Cost', state: 'Excellent' },
            { name: 'Pollination', state: 'Excellent' },
            { name: 'Time', state: 'Good' },
        ],
        cons: [
            { name: 'Animals', state: 'Awful' },
            { name: 'Location', state: 'Awful' },
            { name: 'Children', state: 'Poor' },
        ]
    },
    {
        id: 3,
        imageUrl: primrose_img,
        commonNames: ['Fringed Loosestrife', 'Fringed Yellow Loosestrife'],
        scientificName: 'Lysimachia ciliata',
        localities: ['AB', 'BC', 'MB', 'NB', 'NS', 'NU', 'ON', 'PE', 'QC', 'SK '],
        blooms: ['Jun', 'Jul', 'Aug', 'Sep'],
        establishmentMeans: 'Natural, Non-invasive',
        lifespan: 'Perennial',
        lightRequirements: ['Shade', 'Part Shade'],
        height: '18 to 30 inches ',
        description: [
            'Fringed yellow-loosestrife is an erect to sprawling, often branched perennial, usually 1-2 ft. tall, forming large masses of pale-green, lance-shaped foliage. An erect stem, unbranched or branched, bearing yellow flowers rising on stalks in axils of opposite leaves; leafstalks fringed with spreading hairs. Five-petaled, yellow flowers droop from stalks which arise from the axils of opposite leaves.',
            'The name emphasizes the hairy leafstalks of this wetland plant, which is sometimes placed in the genus Steironema. Southern Loosestrife (L. tonsa) has smooth leafstalks, grows only to 3\'(90 cm) tall, and occurs from Kentucky and Virginia south to Georgia and west to Texas.Lance - leaved Loosestrife(L.lanceolata) has narrow leaves tapering to the base and occurs in a range similar to that of Fringed Loosestrife but not in Canada or the northern Plains states.Trailing Loosestrife(L.radicans) has very weak stems, virtually trailing on the ground, and occurs in the south - central United States east to Florida and Virginia.'],
        waterAmount: ['Medium', 'High'],
        soilMoisture: ['Moist', 'Wet'],
        conditionComments: 'Tolerates seasonal flooding.',
        spacing: '1 to 3 inches',
        seedDepth: '1 to 2 inches',
        plantingTime: 'Any',
        mainPreference: {suggestion: 'Location'},
        pros: [
            { name: 'Location', state: 'Good' },
            { name: 'Pollination', state: 'Good' },
        ],
        cons: [
            { name: 'Animals', state: 'Awful' },
            { name: 'Children', state: 'Awful' },
            { name: 'Cost', state: 'Awful' },
            { name: 'Time', state: 'Poor' },

        ]
    },
    {
        id: 4,
        imageUrl: fall_phlox_img,
        commonNames: ['Fall Phlox', 'Perennial Phlox'],
        scientificName: 'Phlox paniculata',
        localities: ['N/A'],
        blooms: ['Jun', 'Jul', 'Aug'],
        establishmentMeans: 'Natural, Non-invasive',
        lifespan: 'Perennial',
        lightRequirements: ['Sun'],
        height: '3-6 feet',
        description: [
            'Fall phlox is a showy clump-former, reaching a height of 3-4 ft. The pink, lavender, or rarely white flowers are borne in a 4-8 in. wide, terminal cluster. A pyramidal cluster of white to pink or lavender flowers atop a stout, smooth, erect stem. The stem\'s narrow, oval leaves are 4-7 in. long.',
            'If found in the wilds beyond its natural range, this species has probably escaped from cultivation. The plant has been widely used as a medicinal herb; the leaf extract is used as a laxative and for treating boils. Many color forms are found in gardens. The very similar Large-leaved Phlox (P. amplifolia) has a hairy stem, only 6-15 leaf pairs below the flower cluster, and a hairless corolla tube; it is found in the southern Appalachian Mountains.'],
        waterAmount: ['Medium'],
        soilMoisture: ['Moist'],
        conditionComments: 'Plants of this species have furnished the stock for many horticultural varieties. The plant need at least 6 hrs. of sun per day. Powdery mildew is a frequent problem.',
        spacing: '8 to 12 inches',
        seedDepth: '1 to 4 inches',
        plantingTime: 'Any',
        mainPreference: {suggestion: 'Time'},
        pros: [
            { name: 'Cost', state: 'Excellent' },
            { name: 'Time', state: 'Excellent' },
            { name: 'Animals', state: 'Good' },
            { name: 'Location', state: 'Good' },
        ],
        cons: [
            { name: 'Children', state: 'Poor' },
            { name: 'Pollination', state: 'Poor' },
        ]
    },
    {
        id: 5,
        imageUrl: eastern_purple_coneflower_img,
        commonNames: ['Eastern Purple Coneflower', 'Purple Coneflower'],
        scientificName: 'Echinacea purpurea',
        localities: ['ON', 'QC'],
        blooms: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'],
        establishmentMeans: 'Natural, Non-invasive',
        lifespan: 'Perennial',
        lightRequirements: ['Sun', 'Part Shade'],
        height: '2-5 feet',
        description: [
            'A popular perennial with smooth, 2-5 ft. stems and long-lasting, lavender flowers. Rough, scattered leaves that become small toward the top of the stem. Flowers occur singly atop the stems and have domed, purplish-brown, spiny centers and drooping, lavender rays. An attractive perennial with purple (rarely white), drooping rays surrounding a spiny, brownish central disk.',
            'The genus name is from the Greek echinos, meaning "hedgehog," an allusion to the spiny, brownish central disk. The flowers of Echinacea species are used to make an extremely popular herbal tea, purported to help strengthen the immune system; an extract is also available in tablet or liquid form in pharmacies and health food stores. Often cultivated, Purple Coneflower is a showy, easily grown garden plant.'],
        waterAmount: ['Medium'],
        soilMoisture: ['Dry'],
        conditionComments: 'Echinacea is a suitable addition to a prairie garden and attractive in flower arrangements. It is a popular perennial with smooth stems and long-lasting, lavender flowers. Rough, scattered leaves that become small toward the top of the stem. Flowers occur singly atop the stems and have domed, purplish-brown, spiny centers and drooping, lavender rays. Purple coneflower can become very aggressive.',
        spacing: '2 to 6 inches',
        seedDepth: '1 to 4 inches',
        plantingTime: 'Any',
        mainPreference: {warning: 'Location'},
        pros: [
            { name: 'Time', state: 'Good' },
            { name: 'Cost', state: 'Good' },
        ],
        cons: [
            { name: 'Location', state: 'Awful' },
            { name: 'Animals', state: 'Poor' },
            { name: 'Children', state: 'Poor' },
            { name: 'Pollination', state: 'Poor' },
        ]
    },
    {
        id: 6,
        imageUrl: black_eyed_susan_img,
        commonNames: ['Black-eyed Susan', 'Common Black-eyed Susan', 'Brown-eyed Susan', 'Blackeyed Susan'],
        scientificName: 'Rudbeckia hirta',
        localities: ['AB', 'BC', 'MB', 'NB', 'NS', 'ON', 'QC', 'SK'],
        blooms: ['Jun', 'Jul', 'Aug', 'Sep', 'Oct'],
        establishmentMeans: 'Natural, Non-invasive',
        lifespan: 'Annual',
        lightRequirements: ['Sun'],
        height: '1-3 feet',
        description: [
            'This cheerful, widespread wildflower is considered an annual to a short-lived perennial across its range. Bright-yellow, 2-3 in. wide, daisy-like flowers with dark centers are its claim-to-fame. They occur singly atop 1-2 ft. stems. The stems and scattered, oval leaves are covered with bristly hairs. Coarse, rough-stemmed plant with daisy-like flower heads made up of showy golden-yellow ray flowers, with disk flowers forming a brown central cone.',
            'This native prairie biennial forms a rosette of leaves the first year, followed by flowers the second year. It is covered with hairs that give it a slightly rough texture. The Green-headed Coneflower (R. laciniata) has yellow ray flowers pointing downward, a greenish-yellow disk, and irregularly divided leaves.'],
        waterAmount: ['Medium'],
        soilMoisture: ['Moist', 'Dry'],
        conditionComments: 'The cheerful blossoms of the Black-eyed Susans liven up bouquets. This annuals may bloom longer with some afternoon shade. Birds enjoy the ripe seeds. Black-eyed Susan can become aggressive if given too perfect an environment and not enough competition.',
        spacing: '4 to 6 inches',
        seedDepth: '1 to 4 inches',
        plantingTime: 'Any',
        mainPreference: {suggestion: 'Pollination'},
        pros: [
            { name: 'Pollination', state: 'Excellent' },
            { name: 'Location', state: 'Good' },
            { name: 'Animals', state: 'Good' },
        ],
        cons: [
            { name: 'Cost', state: 'Awful' },
            { name: 'Children', state: 'Poor' },
            { name: 'Time', state: 'Poor' },
        ]
    },
];

export default plantDb;

/*
Height: '24-36 in. (60-90 cm)'

Spacing: '15-18 in. (38-45 cm)'

Hardiness:
['USDA Zone 5a: to -28.8 °C (-20 °F)',
'USDA Zone 5b: to -26.1 °C (-15 °F)',
'USDA Zone 6a: to -23.3 °C (-10 °F)',
'USDA Zone 6b: to -20.5 °C (-5 °F)',
'USDA Zone 7a: to -17.7 °C (0 °F)',
'USDA Zone 7b: to -14.9 °C (5 °F)',
'USDA Zone 8a: to -12.2 °C (10 °F)',
'USDA Zone 8b: to -9.4 °C (15 °F)',
'USDA Zone 9a: to -6.6 °C (20 °F)',
'USDA Zone 9b: to -3.8 °C (25 °F)',
'USDA Zone 10a: to -1.1 °C (30 °F)',
'USDA Zone 10b: to 1.7 °C (35 °F)']

Sun Exposure: ['Full Sun', 'Sun to Partial Shade']

Soil pH requirements:
['6.1 to 6.5 (mildly acidic)',
'6.6 to 7.5 (neutral)',
'7.6 to 7.8 (mildly alkaline)']

Patent Information: 'Non-patented'

Propagation Methods: 'By dividing the rootball'

Bloom Time: ['Early (E)', 'Reblooming (Re)']

Flower Size: 'Large (more than 4.5" diameter)'

Blooming Habit: 'Diurnal (diu.)'

Flower Type: 'Single'

Bloom Color: 'Orange'

Color Patterns: 'Blend'

Flower Fragrance: 'Slightly Fragrant'

Foliage Habit: 'Semi-evergreen (sev.)'

Ploidy: Unknown

Awards (if applicable): Unknown

Foliage Color: Unknown

Bloom Characteristics: Unknown

Water Requirements:
'Average Water Needs; Water regularly; do not overwater'

Where to Grow:
'Grow outdoors year-round in hardiness zone'

Regional
This plant is said to grow outdoors in the following regions:
['Auburn, Alabama(3 reports)',
'Birmingham, Alabama',
'Cullman, Alabama',
'Gadsden, Alabama',
'Huntsville, Alabama',
'Madison, Alabama',
'Mobile, Alabama(2 reports)',
'Montgomery, Alabama',
'Piedmont, Alabama',
'Scottsboro, Alabama',
'Vincent, Alabama',
'Flagstaff, Arizona',
'Bismarck, Arkansas',
'Fayetteville, Arkansas',
'Logan Lake, British Columbia',
'Sacramento, California',
'Santa Barbara, California',
'Temecula, California',
'Wildomar, California',
'Colorado Springs, Colorado',
'Denver, Colorado',
'Laporte, Colorado',
'Bear, Delaware',
'Newark, Delaware',
'Ocean View, Delaware',
'Deltona, Florida',
'Gibsonton, Florida',
'Lake City, Florida',
'Marianna, Florida',
'Miccosukee Cpo, Florida',
'Panama City, Florida',
'Tallahassee, Florida',
'Welaka, Florida',
'Braselton, Georgia',
'Canton, Georgia',
'Cordele, Georgia',
'Cornelia, Georgia',
'Hawkinsville, Georgia',
'Homer, Georgia',
'Kingsland, Georgia',
'Roopville, Georgia',
'Snellville, Georgia',
'Stone Mountain, Georgia',
'Bensenville, Illinois',
'Carterville, Illinois',
'Champaign, Illinois',
'Cherry Valley, Illinois',
'Chillicothe, Illinois',
'Hampton, Illinois',
'Hinsdale, Illinois',
'Mt Zion, Illinois',
'Niles, Illinois',
'Spring Grove, Illinois',
'Farmersburg, Indiana',
'Logansport, Indiana',
'Macy, Indiana',
'Newburgh, Indiana',
'Solsberry, Indiana',
'Cedar Rapids, Iowa',
'Davenport, Iowa',
'Iowa City, Iowa',
'Nichols, Iowa',
'Brookville, Kansas',
'Barbourville, Kentucky',
'Calvert City, Kentucky',
'Ewing, Kentucky',
'Fedscreek, Kentucky',
'Hebron, Kentucky',
'Lexington, Kentucky',
'Louisville, Kentucky',
'Mc Dowell, Kentucky',
'Melbourne, Kentucky',
'Paintsville, Kentucky',
'Salvisa, Kentucky',
'Smiths Grove, Kentucky',
'Taylorsville, Kentucky',
'Villers-lÃ¨s-Nancy, Lorraine',
'Baton Rouge, Louisiana',
'Coushatta, Louisiana',
'Hessmer, Louisiana',
'Monroe, Louisiana',
'New Orleans, Louisiana',
'Prairieville, Louisiana',
'Zachary, Louisiana',
'Durham, Maine',
'Fort Kent, Maine',
'Lisbon, Maine',
'South Berwick, Maine',
'Cumberland, Maryland',
'Hughesville, Maryland',
'Laurel, Maryland',
'Pikesville, Maryland',
'Amesbury, Massachusetts',
'Bridgewater, Massachusetts',
'Brimfield, Massachusetts',
'Mashpee, Massachusetts',
'Roslindale, Massachusetts',
'Salem, Massachusetts',
'Sandwich, Massachusetts',
'Weston, Massachusetts',
'Woburn, Massachusetts',
'Caro, Michigan',
'Davison, Michigan',
'Dearborn Heights, Michigan',
'Detroit, Michigan',
'Eastpointe, Michigan',
'Grand Rapids, Michigan',
'Mancelona, Michigan',
'Mount Morris, Michigan',
'Pinconning, Michigan',
'Plainwell, Michigan',
'Royal Oak, Michigan',
'Saginaw, Michigan',
'Saint Clair Shores, Michigan',
'South Lyon, Michigan',
'Traverse City, Michigan',
'Grand Portage, Minnesota',
'Hibbing, Minnesota',
'Minneapolis, Minnesota(3 reports)',
'Sturgeon Lake, Minnesota',
'Gulfport, Mississippi',
'Madison, Mississippi',
'Marietta, Mississippi',
'Bates City, Missouri',
'Cole Camp, Missouri',
'Conway, Missouri',
'Kansas City, Missouri',
'Saint Louis, Missouri',
'Springfield, Missouri',
'Omaha, Nebraska',
'Scottsbluff, Nebraska',
'Colpitts Settlement, New Brunswick',
'Auburn, New Hampshire',
'Exeter, New Hampshire',
'Greenville, New Hampshire',
'Milford, New Hampshire',
'Mont Vernon, New Hampshire',
'Munsonville, New Hampshire',
'Nashua, New Hampshire',
'Newport, New Hampshire',
'North Walpole, New Hampshire',
'Neptune, New Jersey',
'Vincentown, New Jersey',
'Moriarty, New Mexico',
'Roswell, New Mexico',
'Santa Fe, New Mexico',
'Taos, New Mexico',
'Ballston Spa, New York',
'Bronx, New York(2 reports)',
'Churchville, New York',
'Dundee, New York',
'Eden, New York',
'Elba, New York',
'Greene, New York',
'Hornell, New York',
'Jefferson, New York',
'Kew Gardens, New York',
'New Hyde Park, New York',
'Nineveh, New York',
'North Tonawanda, New York',
'Oceanside, New York',
'Ogdensburg, New York',
'Penn Yan, New York',
'Rochester, New York',
'Saranac Lake, New York',
'Saratoga Springs, New York',
'Syracuse, New York',
'West Kill, New York',
'Burlington, North Carolina',
'Concord, North Carolina',
'Denver, North Carolina',
'Elizabeth City, North Carolina',
'Fuquay Varina, North Carolina',
'Graham, North Carolina',
'Hillsborough, North Carolina',
'Lake Toxaway, North Carolina',
'Bucyrus, Ohio(2 reports)',
'Chillicothe, Ohio',
'Cincinnati, Ohio',
'Columbus, Ohio',
'Dayton, Ohio',
'Defiance, Ohio',
'Dundee, Ohio',
'Elyria, Ohio',
'Guysville, Ohio',
'Lynchburg, Ohio',
'Madison, Ohio',
'Newark, Ohio',
'North Ridgeville, Ohio',
'Hulbert, Oklahoma',
'Ninnekah, Oklahoma',
'Greater Sudbury, Ontario',
'Baker City, Oregon',
'Blodgett, Oregon',
'Altoona, Pennsylvania',
'Doylestown, Pennsylvania',
'Irwin, Pennsylvania',
'Langhorne, Pennsylvania',
'Millersburg, Pennsylvania',
'Pottstown, Pennsylvania',
'Upper Darby, Pennsylvania',
'Valencia, Pennsylvania',
'Watsontown, Pennsylvania',
'West Chester, Pennsylvania',
'West Warwick, Rhode Island(2 reports)',
'Conway, South Carolina',
'Prosperity, South Carolina',
'Summerville, South Carolina',
'Wagener, South Carolina',
'Clarksville, Tennessee',
'Clifton, Tennessee',
'Elizabethton, Tennessee',
'Hendersonville, Tennessee',
'Hixson, Tennessee',
'Memphis, Tennessee',
'Murfreesboro, Tennessee',
'Pocahontas, Tennessee',
'Arlington, Texas',
'Belton, Texas',
'Channelview, Texas',
'Colmesneil, Texas',
'Conroe, Texas',
'Coppell, Texas',
'Dallas, Texas(2 reports)',
'Desoto, Texas',
'Fate, Texas',
'Fort Worth, Texas',
'Gainesville, Texas',
'Galveston, Texas',
'Gause, Texas',
'Gilmer, Texas',
'Kingsland, Texas',
'Leander, Texas',
'New Caney, Texas',
'Palestine, Texas',
'Port Neches, Texas',
'Rowlett, Texas',
'Centerville, Utah',
'Salt Lake City, Utah(2 reports)',
'Tremonton, Utah',
'Montpelier, Vermont',
'West Dummerston, Vermont',
'Fancy Gap, Virginia',
'Jonesville, Virginia',
'Pulaski, Virginia',
'Roanoke, Virginia',
'Suffolk, Virginia',
'Vienna, Virginia',
'Virginia Beach, Virginia',
'Wytheville, Virginia',
'Kalama, Washington',
'Olympia, Washington',
'Spokane, Washington',
'Stanwood, Washington',
'Twisp, Washington',
'Liberty, West Virginia',
'Peterstown, West Virginia',
'Dallas, Wisconsin',
'Delavan, Wisconsin',
'Ellsworth, Wisconsin',
'Marinette, Wisconsin',
'New Lisbon, Wisconsin',
'New London, Wisconsin',
'Ogema, Wisconsin',
'Pewaukee, Wisconsin',
'Pulaski, Wisconsin',
'South Milwaukee, Wisconsin',
'Casper, Wyoming',
'Kinnear, Wyoming',
'Riverton, Wyoming',
'Sheridan, Wyoming']
*/

/*
Clockwise from bottom left (with an emphasis on native plants first in each line and then an option for non-native; native species may be all you want to include)
Sisyrinchium angustifolium; Myosotis scorpioides (those are the pale blue flowers)
Symphyotrichum novae-angliae or Polypodium virginianum (both are natives; the former is an aster; the latter is a fern – both would have leaves like the alternate-leaved stuff drawn here)
Chamerion angustifolium (native) or Gladiolus sp
(back pale flowers): Oenothera perennis (native) or  Primula vulgaris
(blue-purple flowers on the right): Amorpha canescens (native) or Phlox panicula
(middle bright purple flowers):  Eupatorium maculatum (native for wetter areas) or  Echinacea purpurea (drier areas; native) or Zinnia sp
Middle yellow flowers: Rudbeckia hirta (native)
*/
