tags:
- name: Sunlight
  description: Sunlight Levels API

paths:
# [GET] sunlight-data
  /sunlight-data:
    get:
      tags:
      - sunlight
      summary: Get sunlight data for a given rectangular landscape
      parameters:
      - name: coords
        in: query
        description: '[latitude, longitude, altitude]'
        required: true
        type: string
        default: '[43, -80.5, 329]'
      - name: res
        in: query
        description: '[x resolution, y resolution]'
        required: true
        type: string
        default: '[10, 10]'
      - name: corners
        in: query
        description: '[[x-min, y-min], [y-min, y-max]]'
        required: true
        type: string
        default: '[[0, 0], [10, 10]]'
      - name: polys
        in: query
        description: '[[[x, y, z]]]'
        required: false
        type: string
      responses:
        200:
          description: 'OK'
          schema:
            type: object
            properties:
              DLIAverages:
                type: array
                description: The average Daily Light Integrals for the landscape over the year
        500:
          description: 'Server Error'

  /sunlight-psnr:
    get:
      tags:
      - sunlight
      summary: Get psnr between the DLI matrix of two landscapes at different resolutions, upscaled to the same resolution
      parameters:
      - name: coords
        in: query
        description: '[latitude, longitude, altitude]'
        required: true
        type: string
        default: '[43, -80.5, 329]'
      - name: res1
        in: query
        description: '[x resolution, y resolution]'
        required: true
        type: string
        default: '[10, 10]'
      - name: res2
        in: query
        description: '[x resolution, y resolution]'
        required: true
        type: string
        default: '[8, 8]'
      - name: corners
        in: query
        description: '[[x-min, y-min], [y-min, y-max]]'
        required: true
        type: string
        default: '[[0, 0], [10, 10]]'
      - name: polys
        in: query
        description: '[[[x, y, z]]]'
        required: false
        type: string
      responses:
        200:
          description: 'OK'
          schema:
            type: object
            properties:
              PSNRs:
                type: array
                description: The PSNRs for each day
              PSNRAverage:
                type: number
                description: The PSNR average
        500:
          description: 'Server Error'

# definitions
# definitions:
#   sunlig:
#     type: object
#     required:
#         - email
#     properties:
#       id:
#         type: integer
#         description: user Id
#       email:
#         type: string
#         description: user Email

schemes:
 - https
 - http
